set mouse=

:color molokai
:nnoremap <silent> <Space> :nohlsearch<Bar>:echo<CR>
:syntax on
:set hlsearch
:set nowrap

" Fix home/end key in all modes
map <esc>OH <home>
cmap <esc>OH <home>
imap <esc>OH <home>
map <esc>OF <end>
cmap <esc>OF <end>
imap <esc>OF <end>

let g:python_highlight_all = 1
let g:molokai_original = 1

" show existing tab with 4 spaces width
set tabstop=4
" when indenting with '>', use 4 spaces width
set shiftwidth=4
" On pressing tab, insert 4 spaces
set expandtab
